### ISSUE TITLE
not recognizing ethernet adapter

### ISSUE THREAD

**Issue by nasi87** [techandme/owncloud-vm#13]
## If you found a bug:

latest VM (16-05-2016) can't run startup script, network test fails:

"Testing if Network is OK...
ifdown: no interface(s) specified"

running ifconfig only shows me interface "lo" but no eth0 or similar.

Older VM (Owncloud 8.2.2) runs fine with same VirtualHost-settings
### Steps to reproduce
1. imported VM
2. run VM with standard settings
### Server configuration

Qnap Virtualization Station running on my NAS
Ethernet Adapter: Intel Gigabit Adapter connected to virtual switch inside my NAS.

**Comment by nasi87** [comment]
Update: running "ifconfig -a" shows me an interface named "ens3" which is down. So I ran:

ifconfig ens3 up
dhclient ens3

Now it works.

**Comment by enoch85** [comment]
Yes, this is known. I still haven't written any code to get this straight. Need to come up with a failproof soulution in bash. 

Thank you for posting this issue!

@ezraholm50 Can you please have a look at this?

**Comment by WaaromZoMoeilijk** [comment]
Work in progress!

Op ma 30 mei 2016 12:51 schreef Daniel Hansson notifications@github.com:

> Yes, this is known. I still haven't written any code to get this straight.
> Need to come up with a failproof soulution in bash.
> 
> Thank you for posting this issue!
> 
> @ezraholm50 https://github.com/ezraholm50 Can you please have a look at
> this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/enoch85/ownCloud-VM/issues/13#issuecomment-222466690,
> or mute the thread
> https://github.com/notifications/unsubscribe/AM4oQHTx6rtmjIi-aNV7HoRBlLuWy6QJks5qGsEmgaJpZM4IpEo0
> .
> 
> ## 

Met vriendelijke groet,

E. Holm

**Comment by nasi87** [comment]
Thanks a lot!

**Comment by enoch85** [comment]
Any update here @ezraholm50? I'm setting up the new server as we speak, so I don't have any time left, sorry for that.

**Comment by WaaromZoMoeilijk** [comment]
Tonight i should have time to test. Will report back.

Op vr 3 jun. 2016 19:58 schreef Daniel Hansson notifications@github.com:

> Any update here @ezraholm50 https://github.com/ezraholm50? I'm setting
> up the new server as we speak, so I don't have any time left, sorry for
> that.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/enoch85/ownCloud-VM/issues/13#issuecomment-223648994,
> or mute the thread
> https://github.com/notifications/unsubscribe/AM4oQBJbkQgGW4cvo2-9mVm1hNDEcH8zks5qIGtRgaJpZM4IpEo0
> .
> 
> ## 

Met vriendelijke groet,

E. Holm

**Comment by enoch85** [comment]
@ezraholm50, no need to test. I have updated the scripts. Just wait 20 minutes and I'll upload e new VM here that you can try.

**Comment by enoch85** [comment]
@nasi87 @ezraholm50 Here you go, the latest package: https://en0ch.se/s/McB32j5Wfw9H4eg/download

**Comment by enoch85** [comment]
Well, any results guys? :)

**Comment by enoch85** [comment]
@nasi87 @ezraholm50 This bug is now fixed. It's confirmed by @G33kDude that had the same issue. --> closing.
