### ISSUE TITLE
new password

### ISSUE THREAD

**Issue by alnpr** [techandme/owncloud-vm#16]
### Steps to reproduce
1. new password not working for linux and ocadmin
### Expected behaviour

Tell us what should happen
new password should be used after the reboot after the successful installation and change of password
### Actual behaviour

Tell us what happens instead
new password and default password not working
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
#### Web server error log

```
Insert your webserver log here
```

**Comment by enoch85** [comment]
Thanks for reporting! Just saying that it doesn't work doesn't tell me much. 

Exactly what steps did you take? Have you tried to re-install it? 

I'm almost certain that you typed the wrong password. Please try again with a fresh install and close this if the problem is gone. Thanks!

**Comment by alnpr** [comment]
hi... tried reinstalling again and it now works.  

thanks!
