### ISSUE TITLE
Error on installation of owncloud

### ISSUE THREAD

**Issue by edafee07** [techandme/owncloud-vm#18]
Hi,

I keep having this error when ever i try to compete the installation of owncloud:

"o working leases in persistent database - sleeping. Network NOT ok. You must have a working Network connection to run this script."

![error](https://cloud.githubusercontent.com/assets/20974871/17640985/66e5feac-6105-11e6-84b4-ae66ef189251.PNG)

Kindly show me how to resolve it.

Kindly send your reply to edafee07@gmail.com

Thank you....

Edafe

**Comment by enoch85** [comment]
@edafee07 Please check in `/etc/network/interfaces` and see which iface you have. Then do `ifconfig` and see if it matches.

**Comment by enoch85** [comment]
PING @edafee07

**Comment by enoch85** [comment]
Feel free to reopen if the issue persist.

**Comment by vipanaque** [comment]
hi. my name is Vanessa, from Ecuador.

i have the same issue, everytime i try to install owncloud with the Pre-configured ownCloud VM, the script "setting correct interface" and show the messages:
_send_packet: network is unreachable
send_packet: please consult README file regarding broadcast address
dhclient.c:2474: Failed to send 300 byte long packet over fallback interface..
..
_Network NOT ok. You must have a working Network connection to run this script.

then I configure the ens33 interface with network permissions, ping to www.google.com, my gateway, etc.. then I run the script again and it set the interface to the original and shows the same message.

please, help me.. I'm new on this.

thanks.
