### ISSUE TITLE
Network NOT ok. You must have a working Network connection to run this script."

### ISSUE THREAD

**Issue by vipanaque** [techandme/owncloud-vm#19]
hi. my name is Vanessa, from Ecuador.

i have the same issue, everytime i try to install owncloud with the Pre-configured ownCloud VM, the script "setting correct interface" and show the messages:
_send_packet: network is unreachable
send_packet: please consult README file regarding broadcast address
dhclient.c:2474: Failed to send 300 byte long packet over fallback interface..
..
_Network NOT ok. You must have a working Network connection to run this script.

then I configure the ens33 interface with network permissions, ping to www.google.com, my gateway, etc.. then I run the script again and it set the interface to the original and shows the same message.

please, help me.. I'm new on this.

thanks.

**Comment by enoch85** [comment]
I'm on vaccation. Please ask @ezraholm50 to help you. 

Thanks!

**Comment by vipanaque** [comment]
@ezraholm50 
hi. my name is Vanessa, from Ecuador.

i have the same issue, everytime i try to install owncloud with the Pre-configured ownCloud VM, the script "setting correct interface" and show the messages:
_send_packet: network is unreachable
send_packet: please consult README file regarding broadcast address
dhclient.c:2474: Failed to send 300 byte long packet over fallback interface..
..
_Network NOT ok. You must have a working Network connection to run this script.

then I configure the ens33 interface with network permissions, ping to www.google.com, my gateway, etc.. then I run the script again and it set the interface to the original and shows the same message.

please, help me.. I'm new on this.

thanks.

**Comment by enoch85** [comment]
@vipanaque Did you manage to solve it? Probably it's an issue with your hypervisor, router, och dhcp client. Please let us know.

**Comment by enoch85** [comment]
This should be solved with https://github.com/enoch85/ownCloud-VM/commit/b2eb7c2d9335025dbb853ec907bd57d27f78adee Please let me know if it isn't solved. Thanks!
