### ISSUE TITLE
Network NOT OK. You must have a working Network connection to run this script

### ISSUE THREAD

**Issue by veloke** [techandme/owncloud-vm#20]
### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Logs

**Web server error log**

```
Insert your webserver log here
```

**Comment by veloke** [comment]
![error1](https://cloud.githubusercontent.com/assets/22819339/19354994/fc2d1eb2-9168-11e6-9b50-03cffad48e41.JPG)

The interface gets an ip from dhcp but script stopts.
hyper-v 2012R2 host

**Comment by veloke** [comment]
can perfectly ping internal ip's including the gateway but not internet ip's

**Comment by veloke** [comment]
dhcp option 121 was causing the issue that the gateway wasn't working.

**Comment by enoch85** [comment]
@veloke What do you mean? Is there a bug, or something we can improve?

**Comment by veloke** [comment]
Yes a small one the script stop with a error on the network when the DHCP sends out routing option 121.

**Comment by enoch85** [comment]
@veloke Do you think you could provide a PR to fix the error?

**Comment by veloke** [comment]
PR? I disabled the DHCP option 121 on a mac reservation and rebooted the appliance and everything performed as wanted.
[cid:image001.png@01D22597.9821FF60]

Dhcp screen:
[cid:image002.png@01D22597.9821FF60]

I have 2 small issues with owncloud it self namely:
1. ```
     I need to add /owncloud after my url (beauty problem)
   ```
2. ```
     I can only use http and the ownloud always tries https (beauty problem)
   ```

**Comment by enoch85** [comment]
@veloke Yeah, Pull Request: https://github.com/enoch85/ownCloud-VM/pulls

Can you upload the images again? I can't see them. :(
1. You need to configure apache
2. You need to configure apache.

**Comment by veloke** [comment]
![1](https://cloud.githubusercontent.com/assets/22819339/19385271/ff0d0084-920d-11e6-96b0-e22e31f6b8db.png)
![2](https://cloud.githubusercontent.com/assets/22819339/19385281/087f9f28-920e-11e6-9991-73bc3ae53164.png)

**Comment by veloke** [comment]
Hi i’ve uploaded the images you should have them.
I’m struggling with the 2 issues
What entry in the config.php are you referring to?
Is it this one? ‘overwrite.cli.url’

**Comment by enoch85** [comment]
Thanks! 

I'm not 100% sure, but yes I think so. You can always try.

And why do you use it over http when you easily can get httpS with Let's Encrypt? It's not recommended to use plain HTTP.
