### ISSUE TITLE
Cant do anything if you need to set a static IP for networking....

### ISSUE THREAD

**Issue by ScottishB** [techandme/owncloud-vm#26]
### Steps to reproduce
1. Connect to a Network that does not have DHCP
2.Boot up the VM
3.Your stuck, the script runs at login and will never complete and no way i can find to stop it.

### Expected behaviour
Login should be provided which does not automatically run the script or the script should ask if you want to run it now or not.

### Actual behaviour
Script runs and there is no way to break it - just hangs setting up the interface

**Comment by enoch85** [comment]
@TheBR Please read the instructions and complete the script.

Here https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L425-L428 and here https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L707-L724

This is not an issue --> closing.

Also, you can press CTRL-C to abort it. And another one, if you don't want it to run directly, modify it. :)

Thanks for posting anyway.

**Comment by ScottishB** [comment]
Hi,
  It doesn't even get that far in the script - it hangs here - you cannot even break out the script - it just sits there for ever:-

```
# Check network
echo "Testing if network is OK..."
service networking restart
    curl -s http://github.com > /dev/null
if [ $? -eq 0 ]
then
    echo -e "\e[32mOnline!\e[0m"
else
echo "Setting correct interface..."
# Set correct interface
{ sed '/# The primary network interface/q' /etc/network/interfaces; printf 'auto %s\niface %s inet dhcp\n# This is an autoconfigured IPv6 interface\niface %s inet6 auto\n' "$IFACE" "$IFACE" "$IFACE"; } > /etc/network/interfaces.new
mv /etc/network/interfaces.new /etc/network/interfaces
service networking restart
fi
```

The echo "Setting correct interface..." is the last thing you see....

Regards

Scott

**Comment by enoch85** [comment]
Ok, but since that fails - remove it and set static IP yourself.
