### ISSUE TITLE
typo in lets-encrypt/activate-ssl.sh

### ISSUE THREAD

**Issue by fisherwei** [techandme/owncloud-vm#30]
[https://github.com/techandme/owncloud-vm/blob/master/lets-encrypt/activate-ssl.sh#L184](url)

Line 184:

`    <Directory $oCPATH>`

should be

`    <Directory $OCPATH>`

**Comment by enoch85** [comment]
Thanks! :+1: I will go through all the script once again when the Nextcloud scripts are updated and 12 is released.

**Comment by enoch85** [comment]
Updated the whole scripts instead: https://github.com/techandme/owncloud-vm/pull/31
