### ISSUE TITLE
Unable to update to latest version.

### ISSUE THREAD

**Issue by armandfishti** [techandme/owncloud-vm#38]
## Steps to reproduce
1.downlod .ova and import it to virtualbox
2.run the update script to update owncloud (tried)
3.brakes the installation and mariadb as in screenshots

## Expected behaviour
should update owncloud to 

## Actual behaviour
Tell us what happens instead

## Server configuration

**Server version:** (see your admin page)
10.0.4
**VM version** (master / released version)
5.2.6

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**
static IP

**Is port 80 and/or 443 open?**
yes
#### Log file (/var/ocdata/owncloud.log)
```
Insert your owncloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

![1](https://user-images.githubusercontent.com/11904502/38358323-3144e102-38c5-11e8-967b-b121415c1083.PNG)
![2](https://user-images.githubusercontent.com/11904502/38358324-315fa8ac-38c5-11e8-87bb-cb9fb763da7b.PNG)
![3](https://user-images.githubusercontent.com/11904502/38358325-317d2922-38c5-11e8-8923-bf68c3a198cf.PNG)
![4](https://user-images.githubusercontent.com/11904502/38358326-3199d130-38c5-11e8-8226-1b1ff6475f09.PNG)

**Comment by enoch85** [comment]
Hmm, this seems more like a import issue of the OVA than a script error to me. As you can see you are on a "read-only filesystem" which probably is the case because the disk is full.

Can you run `sudo df -h` and post the output?

**Comment by armandfishti** [comment]
First of all, thank you for the very quick answer.

![image](https://user-images.githubusercontent.com/11904502/38358875-cf7acbb0-38c6-11e8-85fe-7fe719c9d593.png)

here is the output.
I have tried the same ova in different machines with virtualbox and vmware , and the same porblem.

**Comment by enoch85** [comment]
Hmm, ok, I haven't run the ownCloud VM for a while since this: https://www.techandme.se/owncloud-10-0-4-last-vm-version/

In other words, ownCloud is not supported anymore and I will not update anything big. Maybe, maybe, maaaybe smaller fixes. :)

**Comment by enoch85** [comment]
I'd suggest to run the Nextcloud VM instead. You can find it here: https://github.com/nextcloud/vm

**Comment by enoch85** [comment]
So, if you find out what's causing it, send a PR to this repo and I'll have a look. 

Thanks! :)

**Comment by armandfishti** [comment]
Thank you.

I have a running owncloud with around 150GB of information and can't switch easy to nextcloud.

I was using your installation (owncloud 9.1.5) wich worked perfectly on VM on a Ubuntu environment but lately users (5-7) started complaining about files not being saved on latest version that has been modified and thought to make an upgrade.

Anyway thank you :)

**Comment by enoch85** [comment]
The upgrade (yes, it is an upgrade) to Nextcloud is very easy. Just run the [migration tool](https://nextcloud.com/migration/) and you're all set. Make sure to do backups first though.
