### ISSUE TITLE
Unable to share with nonadmin user or group

### ISSUE THREAD

**Issue by martin20h** [techandme/owncloud-vm#5]
## If you found a bug:

I am not able to shate to group or to user, who is not member of admin group

![oc err](https://cloud.githubusercontent.com/assets/18466105/14532932/34c7b1b4-0263-11e6-82e1-654293f59e8d.png)
![oc err2](https://cloud.githubusercontent.com/assets/18466105/14532931/34c7960c-0263-11e6-988b-d3ff90028e04.jpg)
### Expected behaviour

Be able to share to all members and groups
### Actual behaviour

I am unable to share folder with anybody expect admins group and it's members.
### Server configuration

**Operating system**:
Ubuntu Linux 14.04.4
**Web server:**
Apache version 2.4.7
**Database:**
MySQL version 5.6.28
**PHP version:**
Apache version 2.4.7
**OwnCloud:**
ownCloud 9.0.1 (stable)
:

**Comment by enoch85** [comment]
@martin20h Thanks for you report! I will have a look at this later tonight.

Is it possible to share _from_ the test user _to_ ocadmin? And have you logged in as test before you tried to share from ocadmin to the test user?

**Comment by martin20h** [comment]
Thank you. As I was looking through settings, I discovered, that when I am member of a test group, I can share to test group, when not -  I am unable to share to test group despite the fact that I am admin -> me = noob.... I am so sorry for bothering you.
Thank you !

**Comment by enoch85** [comment]
Thanks for sorting that out @martin20h. Enjoy your VM and please ask if you have further questions.
