### ISSUE TITLE
Combinded effors, configuration managment

### ISSUE THREAD

**Issue by ypid** [techandme/owncloud-vm#6]
I just stumbled across your build scripts and wanted to make you aware of the [DebOps project](http://debops.org/). It could be used to build a VM. The advantage is that we could combined our efforts and with that achieve a higher quality. I realize that getting into Ansible and all that is not easy but maybe you like it.
https://github.com/debops/ansible-owncloud/

You can checkout https://github.com/carlalexander/debops-wordpress for an end user oriented project based on DebOps.

**Comment by enoch85** [comment]
What are the benefits of DebOps compared to doing stuff like we do today? Would I have to change from Bash to Ansible?

**Comment by ypid** [comment]
Yes that would require to learn a new tool. Ansible has it’s own ways of doing things using modules instead of shell commands. But with that, you get a lot of benefits as I think:
- Better readability, comments.
- Code is bundled in roles and can be reused. Not only to provision VMs like it would be used for this project, but also to deploy ownCloud instances manually. That pays-off in the longer run I would say. ~~Or how would you deploy ownCloud on a Raspberry Pi (assuming you don’t want to run a Hypervisor on it)~~?
- Resulting form the previous point: More users/sysadmins use the code and maintain it.
- Ansible being a CM system can later be used to customize the VM/ownCloud in individual projects. You can include proven settings in your global inventory configuration and deploy them on all your instances. This is something I am interested in :wink:
- All roles of the DebOps project are tested using integration testing (testing of the ownCloud role can be improved but it is a start).

**Comment by enoch85** [comment]
> •Better readability, comments.

I could fix this by just intendent better than I do now. Almost non of my code are intendeted, but I´m planning on doing that later on. Regarding the comments, you can just `# <comment>` if you want.

> •Code is bundled in roles and can be reused. Not only to provision VMs like it would be used for this project, but also to deploy ownCloud instances manually. That pays-off in the longer run I would say. Or how would you deploy ownCloud on a Raspberry Pi (assuming you don’t want to run a Hypervisor on it)?

This VM(s) is built in a way that allows both manual and automatic installation. I have chosen not to use Vagrant or similar software. What I do is using the same VM and build from that every time a do a new release.

> More users/sysadmins use the code and maintain it.

Do you think there are more peopple that can code in Ansible than in Bash?

**All and all** it seems it would require a lot of work to move to DebOps for scripts that are already working. And you haven't convinced me, yet. :)

**Comment by ypid** [comment]
I know it is an advanced topic and I don’t mind when you want to avoid to "change a running system". I myself have such a "running system" https://github.com/jchaney/owncloud/

> Do you think there are more peopple that can code in Ansible than in Bash?

No. But there are just more people using the Ansible code as it can be used for so many different things. This also leads to a more secure deployment. Example: https://github.com/owncloud/vm/issues/45

> I could fix this by just intendent better than I do now. Almost non of my code are intendeted, but I´m planning on doing that later on. Regarding the comments, you can just # <comment> if you want.

No question you can do that, but Ansible kind of pushes you a bit more to do that from the beginning.

**Comment by ypid** [comment]
Let me emphasize one point. Maintainability. I have used install scripts in bash before and they just are not as good as a proper CM system for this job. With Ansible, the maintenance work can be offloaded to all the sysadmins using it. The build scripts can only be run once to provision the VM.

**Comment by enoch85** [comment]
Ok, I get your point, sort of. Can you code Ansible? And does Ansible work kind of like Bash, I mean is it the same "code family?"

The whole point of my scripts are that they should just work so that practically anyone can just `wget script.sh` and `sudo bash scrpt.sh`. That's how it works now anyway. You are talking about maintaining, and the base for this is already done here. I change version number when a new release is out, that's about it. That is if I don't want to add a new function, then I have to develop it ofc. Have you tried running the scripts? If not, just get `owncloud_install_production-sh` and run it inside a VM with Ubuntu Server 14.04 on. You will see, it just works (If you find any bugs, please let me know).

My scripts provide the whole ownCloud install on a fresh server, and when the server is setup I have nothing to do with it, except if they buy support and such. I'm not sure if you mean maintaining stuff after the scripts are run?

Nice project btw (Docker)! Do you want to be a part of Tech and Me and release your Docker container there? We have around 1000 unique visitors per day as of today. We are actually looking for guys like you that could contribute with knowledge, guides and stuff like that. We are paid through donations, or work we do from people buying stuff in the shop.

**Comment by ypid** [comment]
> Ok, I get your point, sort of. Can you code Ansible? And does Ansible work kind of like Bash, I mean is it the same "code family?"

It is different. Both in mentality and in code. The file format is YAML and you describe a state with Ansible and Ansible ensures the state how you want it to be is present. I do know a fare bit of Ansible by now I would say. I looked into the other CM systems before I settled on Ansible. Ansible is the easiest to get started with.

> The whole point of my scripts are that they should just work so that practically anyone can just wget script.sh and sudo bash scrpt.sh

I get your point. Using a fully blown CM system together with something like the DebOps project is advanced sure, but I believe it gets you a different level of quality. I am involved in the DebOps project for over one year now and we have pretty solid quality standards I hope :wink:

> Have you tried running the scripts?

I have not, thats what I have Ansible for :wink:

> Nice project btw (Docker)! Do you want to be a part of Tech and Me and release your Docker container there?

Thanks! You can use the Docker image in terms of the AGPL-3.0, that is fine with me. And thanks for the offer, but I am giving enough ownCloud support already :smile:

**Comment by enoch85** [comment]
> It is different.

To say at least. I looked at the code and I got it kind of, but where do I generate random passwords e.g? From my POV there seems to be a lot of stuff that you _can't_ do in Ansible that you can do in Bash. Am I right?

> I have not, thats what I have Ansible for

Ofc, but if you tried the scripts you would see the quality. Or if you can read bash, just check what it does at least. :)

> but I am giving enough ownCloud support already

You can never give too much ;)

Anyway, I'm not eager to learn a new language right now. But I could give you tips and hints to your project. What could you do for me in return? How do you think we could collaborate doing two different languages?

**Comment by ypid** [comment]
> To say at least. I looked at the code and I got it kind of, but where do I generate random passwords e.g? From my POV there seems to be a lot of stuff that you can't do in Ansible that you can do in Bash. Am I right?

Sure you can do that. Ansible has a way to [lookup random passwords](https://docs.ansible.com/ansible/playbooks_lookups.html#the-password-lookup)
But you are right, it would take some effort.

> Ofc, but if you tried the scripts you would see the quality. Or if you can read bash, just check what it does at least. :)

I looked into them.

> You can never give too much ;)

Don’t worry. :wink: 

I just wanted to give you a hint, that’s all. I have a ownCloud VM setup that I am currently working with and implementing. Only the template VM building part is not as automated as I would like it to be (but I don’t have to do that anymore since I can keep the deployed instances and the template up to date with Ansible). Never mind. Thanks for you feedback.

**Comment by enoch85** [comment]
Thank _you_. :+1:
